services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: movilidad-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: tfm_password
      POSTGRES_DB: movilidad_urbana
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/home/postgres/pgdata/data
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: movilidad-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tfm.com
      PGADMIN_DEFAULT_PASSWORD: tfm_password
    ports:
      - "8080:80"
    depends_on:
      - timescaledb

  grafana:
    image: grafana/grafana-oss:latest
    container_name: movilidad-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb

volumes:
  timescale_data:
